; ==========================================
; PlatformIO Configuration File
; Teensy 4.0 Gyro Joystick Project
; ==========================================

[env:teensy40]

; ==========================================
; Target Platform + Board
; ==========================================
platform = teensy
board = teensy40

; ==========================================
; Framework
; ==========================================
framework = arduino

; ==========================================
; Serial Monitor
; ==========================================
monitor_speed = 115200

; ==========================================
; Upload Speed
; ==========================================
upload_speed = 115200

; ==========================================
; USB HID Configuration
; Enables Teensy Joystick Mode
; ==========================================
build_flags =
    -D USB_JOYSTICK

; ==========================================
; Required Libraries
; ==========================================
lib_deps =
    sparkfun/SparkFun 9DoF IMU Breakout - ICM 20948 - Arduino Library@^1.3.2
    adafruit/Adafruit BusIO@^1.17.4


